# H2 Database Configuration
spring.datasource.url = jdbc:h2:file:./data/employeedbtest
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.datasource-platform=org.hibernate.dailect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql = true
spring.h2.console.path=/h2-console



## SQL scripts
sql.script.create.employee1=insert into employee ( first_name , last_name , email )\
  values ( 'kareem' , 'yasser' , 'kareem@gmail.com' )
sql.script.create.employee2=insert into employee ( first_name , last_name , email )\
  values ( 'amr' , 'adel' , 'amr@gmail.com' )
sql.script.create.employee3=insert into employee ( first_name , last_name , email )\
  values ( 'nagy' , 'galal' , 'nagy@outlook.com' )

sql.script.delete.employee = DELETE FROM EMPLOYEE ;ALTER TABLE EMPLOYEE ALTER COLUMN ID RESTART WITH 1